config/routes.rb
Blog::Application.routes.draw do
  get "posts/login"

  resources :posts
  root to: "posts#index"
  match '/login' => 'Posts#login', :as => 'login', :via => 'get'
  match '/admin' => 'Posts#admin', :as => 'admin', :via => 'get'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def login
  end

  def index
  end

  def admin
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Room Management</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body   style="background: #dedede">

	<%if current_page?(admin_path) %>
<div class="navbar navbar-inverse" style="position: static;">
              <div class="navbar-inner">
                <div class="container">
                  <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-inverse-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </a>
                  <a class="brand" href="#" style="font-size:16px;">Room Management System</a>
                  <div class="nav-collapse collapse navbar-inverse-collapse">
                    <ul class="nav">
                      <li class="active"><a href="#">Main</a></li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Room <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                          <li><a href="#">List Room</a></li>
                          <li><a href="#">Add Room</a></li>
                          <li><a href="#">Edit Room</a></li>
                          <li class="divider"></li>
                          <li class="nav-header">Nav header</li>
                          <li><a href="#">Separated link</a></li>
                          <li><a href="#">One more separated link</a></li>
                        </ul>
                      </li>
                    </ul>

                    <ul class="nav pull-right">
                      <li><a href="#">Welcome! admin</a></li>
                      <li class="divider-vertical"></li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Setting <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                          <li><a href="#">Change Password</a></li>
                          <li><a href="#">Login History</a></li>
                          <li class="divider"></li>
                          <li><a href="#">Logout</a></li>
                        </ul>
                      </li>
                    </ul>
                  </div><!-- /.nav-collapse -->
                </div>
              </div><!-- /navbar-inner -->
            </div>
	<% end %>


	<!--- head and navbar -->
	<div class="navbar">

      <div class="navbar-inner">
      	<a class="brand" href="/"><%= image_tag('logo-trans.png') %></a>
      </div>
      <% if !current_page?(admin_path)%>
      	<ul class="breadcrumb">

      		<li class="active"><i class="icon-home icon-white"></i> Home <span class="divider">|</span></li>
		    <li><i class="icon-plus"></i><%= link_to " Booking ", '/' %><span class="divider">|</span></li>
		    <li><i class="icon-wrench"></i><%= link_to " Admin ", login_path %><span class="divider">|</span></li>
	    </ul>
	  <% end %>

    </div>


    <%= yield %>

	<!--footer section-->
	<div id="footer">
		© 2012 Faculty of Engineering
					Thammasat University
	</div>

	
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/admin.html.erb
    <!--- body section -->
    
    <div class="container-fluid">
        <div class="well">

      <div class="row-fluid">
        <!--Sidebar content-->
        <div class="span2">

               <ul class="nav nav-list">
                <li class="nav-header">Room Edit</li>
                <li><a href="#">List Room</a></li>
                <li><a href="#">Add Room</a></li>
                <li><a href="#">Edit Room</a></li>
                <li class="nav-header">Setting</li>
                <li><a href="#">Change Password</a></li>
                <li><a href="#">Login History</a></li>
                <li class="divider"></li>
                <li><a href="#">Logout</a></li>
              </ul>


        </div>
        <!--Sidebar content-->

        <!--Body content-->
        <div class="span10">
            <div class="hero-unit">
                <h1>Room Reservation Online</h1>
                <p>Faculty of Engineering , Thammasat University</p>
            </div>
        </div>
        <!--Body content-->
      </div>
    </div>

</div>

app/views/posts/admin/admin.html.erb
<div class="navbar navbar-inverse" style="position: static;">
              <div class="navbar-inner">
                <div class="container">
                  <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-inverse-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </a>
                  <a class="brand" href="#">Title</a>
                  <div class="nav-collapse collapse navbar-inverse-collapse">
                    <ul class="nav">
                      <li class="active"><a href="#">Home</a></li>
                      <li><a href="#">Link</a></li>
                      <li><a href="#">Link</a></li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                          <li><a href="#">Action</a></li>
                          <li><a href="#">Another action</a></li>
                          <li><a href="#">Something else here</a></li>
                          <li class="divider"></li>
                          <li class="nav-header">Nav header</li>
                          <li><a href="#">Separated link</a></li>
                          <li><a href="#">One more separated link</a></li>
                        </ul>
                      </li>
                    </ul>
                    <form class="navbar-search pull-left" action="">
                      <input type="text" class="search-query span2" placeholder="Search">
                    </form>
                    <ul class="nav pull-right">
                      <li><a href="#">Link</a></li>
                      <li class="divider-vertical"></li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                          <li><a href="#">Action</a></li>
                          <li><a href="#">Another action</a></li>
                          <li><a href="#">Something else here</a></li>
                          <li class="divider"></li>
                          <li><a href="#">Separated link</a></li>
                        </ul>
                      </li>
                    </ul>
                  </div><!-- /.nav-collapse -->
                </div>
              </div><!-- /navbar-inner -->
            </div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
	<!--- body section -->
	<div class="container-fluid">
		<div class="well">
		  <div class="row-fluid">
		  	<!--Sidebar content-->
		    <div class="span3">
		    		<form>
					  <fieldset>
					    <legend><i class="icon-search"></i> Search Room</legend>
					    <input type="text" placeholder="Date…"> <br>
					    <input type="text" placeholder="Room…"> <br>
					    <div class="alert alert-success" style="width:170px;">Example: วศ.301</div>
					    <button class="btn btn-primary" type="button">Search...</button>
					  </fieldset>
					</form>
		    </div>
		    <!--Sidebar content-->

		    <!--Body content-->
		    <div class="span9">
				<div class="hero-unit">
	                <h1>Room Reservation Online</h1>
	                <p>Faculty of Engineering , Thammasat University</p>
	        	</div>
			</div>
		    
		    <!--Body content-->
		  </div>
		</div>
	</div>

app/views/posts/login.html.erb
  <!--- body section -->
  <div class="container-fluid">
    <div class="well">
    <div class="row-fluid">
      <!--Sidebar content-->
      <div class="span3">
        

          <form>
          <fieldset>
            <legend><i class="icon-search"></i> Search Room</legend>
            <input type="text" placeholder="Date…"> <br>
            <input type="text" placeholder="Room…"> <br>
            <div class="alert alert-success" style="width:170px;">Example: วศ.301</div>
            <button class="btn btn-primary" type="button">Search...</button>
          </fieldset>
        </form>


      </div>
      <!--Sidebar content-->

      <!--Body content-->
      <div class="span9">
            <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>Warning!</strong> Please enter your email and username.
          </div>

            <form class="form-horizontal">
            <div class="control-group">
              <label class="control-label" for="inputEmail">Email</label>
              <div class="controls">
                <input type="email" id="inputEmail" placeholder="Email" required>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label" for="inputPassword">Password</label>
              <div class="controls">
                <input type="password" id="inputPassword" placeholder="Password">
              </div>
            </div>
            <div class="control-group">
              <div class="controls">
                <label class="checkbox">
                  <input type="checkbox"> Remember me
                </label>
                <button type="submit" class="btn btn-primary">Sign in</button>
              </div>
            </div>
          </form>

          </div>
      </div>
      <!--Body content-->
    </div>
    </div>
  </div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Body:</b>
  <%= @post.body %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>